name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
      - herstel1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to Raspberry Pi
        run: |
          scp -i ~/.ssh/id_rsa_github_action -o StrictHostKeyChecking=no -r . pi@192.168.0.70:~/docker/dev/rss/rss_dashboard_login

      - name: Restart Docker container
        run: |
          ssh -i ~/.ssh/id_rsa_github_action -o StrictHostKeyChecking=no pi@192.168.0.70 << 'EOF'
          cd ~/docker/dev/rss/rss_dashboard_login
          docker-compose down
          docker-compose up -d
          EOF

