name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - extra-feeds
      - herstel1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no pi@192.168.0.70 << 'EOF'
          cd ~/docker/dev/rss/rss_dashboard_login
          git fetch origin
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          docker compose down
          docker compose up -d --build
          EOF

