name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - extra-feeds

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd ~/docker/dev/rss/rss_dashboard_login
          git pull origin extra-feeds
          docker-compose down
          docker-compose up -d --build
