name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - extra-feeds

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: |
          cd ~/docker/dev/rss/rss_dashboard_login
          git pull origin extra-feeds
          docker compose down
          docker compose up -d --build

